# Generated by Django 4.2.13 on 2024-05-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aidrequests', '0001_initial'),
        ('aiddeliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiddelivery',
            name='aid_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidrequests.aidrequest'),
        ),
    ]
